services:
  # zookeeper: 카프카 브로커를 관리
  # 최근 카프카는 주키퍼가 없어도 돌아가지만, 학습할 때는 주키퍼가 안정적
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181      # 클라이언트가 붙을 포트
      ZOOKEEPER_TICK_TIME: 2000        # 하트비트 주기 (ms)

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      # 🌟 리스너 2개 — 프로토콜 맵, 실제 리스너, 광고 리스너 3종 세트
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

# http://localhost:8080 로 접속해서 확인
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8080:8080"
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092    # 👈 내부 리스너 포트

# 접속 시도 (Handshake): 스프링 앱이 localhost:9092로 접속
# 정보 확인 (Metadata): "나 로그 보내고 싶은데, 누구한테 보내면 돼?"
# 카프카 대답: "나는 localhost:9092야!" ← KAFKA_ADVERTISED_LISTENERS가 이걸 알려줌

