version: '3'
services:
#  zookeeper : 카프카 브로커를 관리
#  최근 카프카는 주키퍼가 없어도 돌아가지만, 학습할 때는 주키퍼를 사용하는 것이 안정적이라고함.
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes # 보안 설정 없이 누구나 로그인가능 하게 설정해주는 것

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes # 데이터 암호화 하지않고, 평문으로 주고받는 것 허용 (보안 신경x)
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092 # 카프카가 내부적으로 9092 포트에서 귀를 기울이고 있는 상태
    depends_on:
      - zookeeper

# 접속 시도 (Handshake): 스프링 앱이 localhost:9092로 접속합니다. (이때 ports 설정이 쓰임.)
# 정보 확인 (Metadata): 스프링 앱이 묻습니다. "나 로그 좀 보내고 싶은데, 누구한테 보내면 돼?"
# 카프카의 대답: 카프카가 자기소개를 하며 답합니다. "안녕! 나는 'localhost:9092'라고 해. 나한테 보내면 돼!"
#    -> - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092 임.